#define TIMER1_HANDLE &htim1
#define TIMER2_HANDLE &htim2
#define TIMER3_HANDLE &htim3
#define TIMER4_HANDLE &htim4

#define FAN1_PWM_TIMER TIMER1_HANDLE
#define FAN1_PWM_CHANNEL TIM_CHANNEL_1
#define FAN1_PWM_PORT GPIOA
#define FAN1_PWM_PIN GPIO_PIN_8
#define FAN1_IC_TIMER TIMER2_HANDLE
#define FAN1_IC_CHANNEL TIM_CHANNEL_1
#define FAN1_IC_CHANNEL_ACTIVE HAL_TIM_ACTIVE_CHANNEL_1

#define FAN2_PWM_TIMER TIMER1_HANDLE
#define FAN2_PWM_CHANNEL TIM_CHANNEL_2
#define FAN2_PWM_PORT GPIOA
#define FAN2_PWM_PIN GPIO_PIN_9
#define FAN2_IC_TIMER TIMER2_HANDLE
#define FAN2_IC_CHANNEL TIM_CHANNEL_2
#define FAN2_IC_CHANNEL_ACTIVE HAL_TIM_ACTIVE_CHANNEL_2

#define FAN3_PWM_TIMER TIMER4_HANDLE
#define FAN3_PWM_CHANNEL TIM_CHANNEL_1
#define FAN3_PWM_PORT GPIOB
#define FAN3_PWM_PIN GPIO_PIN_6
#define FAN3_IC_TIMER TIMER3_HANDLE
#define FAN3_IC_CHANNEL TIM_CHANNEL_1
#define FAN3_IC_CHANNEL_ACTIVE HAL_TIM_ACTIVE_CHANNEL_1

#define FAN4_PWM_TIMER TIMER4_HANDLE
#define FAN4_PWM_CHANNEL TIM_CHANNEL_2
#define FAN4_PWM_PORT GPIOB
#define FAN4_PWM_PIN GPIO_PIN_7
#define FAN4_IC_TIMER TIMER3_HANDLE
#define FAN4_IC_CHANNEL TIM_CHANNEL_2
#define FAN4_IC_CHANNEL_ACTIVE HAL_TIM_ACTIVE_CHANNEL_2

#define FAN5_PWM_TIMER TIMER4_HANDLE
#define FAN5_PWM_CHANNEL TIM_CHANNEL_3
#define FAN5_PWM_PORT GPIOB
#define FAN5_PWM_PIN GPIO_PIN_8
#define FAN5_IC_TIMER TIMER3_HANDLE
#define FAN5_IC_CHANNEL TIM_CHANNEL_3
#define FAN5_IC_CHANNEL_ACTIVE HAL_TIM_ACTIVE_CHANNEL_3

#define FAN6_PWM_TIMER TIMER4_HANDLE
#define FAN6_PWM_CHANNEL TIM_CHANNEL_4
#define FAN6_PWM_PORT GPIOB
#define FAN6_PWM_PIN GPIO_PIN_9
#define FAN6_IC_TIMER TIMER3_HANDLE
#define FAN6_IC_CHANNEL TIM_CHANNEL_4
#define FAN6_IC_CHANNEL_ACTIVE HAL_TIM_ACTIVE_CHANNEL_4

